# --------------------------
# Minimal SymOp stub — factory
# --------------------------

def make_perm_symop(n: int):
    """Return a SymOp class for permutations on n points."""

    class SymOpPerm:
        __slots__ = ("perm",)

        def __init__(self, perm):
            self.perm = tuple(perm)

        @classmethod
        def identity(cls):
            return cls(tuple(range(n)))

        def inv(self):
            r = [None] * n
            for i, p in enumerate(self.perm):
                r[p] = i
            return self.__class__(tuple(r))

        def __mul__(self, other):
            p, q = self.perm, other.perm
            return self.__class__(tuple(p[q[i]] for i in range(n)))

        def __eq__(self, other):
            return isinstance(other, self.__class__) and self.perm == other.perm

        def __hash__(self):
            return hash(self.perm)

        def __repr__(self):
            return f"Perm{n}{self.perm}"

        def to_string(self):
            return repr(self)

    SymOpPerm.__name__ = f"SymOpPerm{n}"
    SymOpPerm.__qualname__ = f"SymOpPerm{n}"
    return SymOpPerm




# --------------------------
# Generators
# --------------------------


def s3_generators():
    SymOpPerm3 = make_perm_symop(3)
    # S3 generated by transpositions s=(01), t=(12) (both involutions)
    e = SymOpPerm3.identity()
    s = SymOpPerm3((1, 0, 2))  # (01)
    t = SymOpPerm3((0, 2, 1))  # (12)
    return e, s, t


def c4_generator():
    SymOpPerm4 = make_perm_symop(4)
    # C4 generated by rotation r = (0 1 2 3)
    e = SymOpPerm4.identity()
    r = SymOpPerm4((1, 2, 3, 0))
    return e, r

